### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by carolinehardin** [carolinehardin/AERAPlanning#1]
- [x] Dried fruit
- [x] nuts (no sunflower seeds)
- [x] beef jerky
- [x] bagels
- [ ] deli cheese
- [ ] deli meat
- [x] disposable diapers
- [ ] small peanutbutter

**Comment by grantdobbe** [comment]
Will purchase meat/cheese in Chicago. We also have half a jar of peanut butter in the cupboard that I'd like to use up.
